site_name: JITORM
site_url: https://jitorm.akarkode.com
nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
